export const ORM_SERVICE = Symbol('ORM_SERVICE');

export const MODULE_OPTIONS_TOKEN = Symbol('MODULE_OPTIONS_TOKEN');
export const CONTROLLER_OPTIONS_TOKEN = Symbol('CONTROLLER_OPTIONS_TOKEN');

export const CURRENT_ENTITY = Symbol('CURRENT_ENTITY');
export const ENTITY_PARAM_MAP = Symbol('ENTITY_PARAM_MAP');

export const ZOD_INPUT_QUERY_SCHEMA = Symbol('ZOD_INPUT_QUERY_SCHEMA');
export const ZOD_QUERY_SCHEMA = Symbol('ZOD_INPUT_QUERY_SCHEMA');
export const ZOD_POST_SCHEMA = Symbol('ZOD_POST_SCHEMA');
export const ZOD_PATCH_SCHEMA = Symbol('ZOD_PATCH_SCHEMA');
export const ZOD_POST_RELATIONSHIP_SCHEMA = Symbol(
  'ZOD_POST_RELATIONSHIP_SCHEMA'
);
export const ZOD_PATCH_RELATIONSHIP_SCHEMA = Symbol(
  'ZOD_PATCH_RELATIONSHIP_SCHEMA'
);
export const ZOD_META_SCHEMA = Symbol('ZOD_META_SCHEMA');

export const FIND_ONE_ROW_ENTITY = Symbol('FIND_ONE_ROW_ENTITY');
export const CHECK_RELATION_NAME = Symbol('CHECK_RELATION_NAME');
export const RUN_IN_TRANSACTION_FUNCTION = Symbol(
  'RUN_IN_TRANSACTION_FUNCTION'
);
