export const CURRENT_ENTITY_MANAGER_TOKEN = Symbol(
  'CURRENT_ENTITY_MANAGER_TOKEN'
);
export const GLOBAL_MODULE_OPTIONS_TOKEN = Symbol('GLOBAL_MODULE_OPTIONS');
export const ORM_SERVICE = Symbol('ORM_SERVICE');
export const ORM_SERVICE_PROPS = Symbol('ORM_SERVICE_PROPS');

export const PARAMS_FOR_ZOD_SCHEMA = Symbol('PARAMS_FOR_ZOD_SCHEMA');
export const FIELD_FOR_ENTITY = Symbol('FIELD_FOR_ENTITY');
export const CONTROL_OPTIONS_TOKEN = Symbol('CONTROL_OPTIONS_TOKEN');
export const RUN_IN_TRANSACTION_FUNCTION = Symbol(
  'RUN_IN_TRANSACTION_FUNCTION'
);

export const CURRENT_ENTITY = Symbol('CURRENT_ENTITY');
export const FIND_ONE_ROW_ENTITY = Symbol('FIND_ONE_ROW_ENTITY');
export const CHECK_RELATION_NAME = Symbol('CHECK_RELATION_NAME');

export const ZOD_INPUT_QUERY_SCHEMA = Symbol('ZOD_INPUT_QUERY_SCHEMA');
export const ZOD_QUERY_SCHEMA = Symbol('ZOD_INPUT_QUERY_SCHEMA');
export const ZOD_POST_SCHEMA = Symbol('ZOD_POST_SCHEMA');
export const ZOD_PATCH_SCHEMA = Symbol('ZOD_PATCH_SCHEMA');
export const ZOD_POST_RELATIONSHIP_SCHEMA = Symbol(
  'ZOD_POST_RELATIONSHIP_SCHEMA'
);
export const ZOD_PATCH_RELATIONSHIP_SCHEMA = Symbol(
  'ZOD_PATCH_RELATIONSHIP_SCHEMA'
);
