export const JSON_API_DECORATOR_ENTITY = Symbol('JSON_API_ENTITY');
export const JSON_API_DECORATOR_OPTIONS = Symbol('JSON_API_OPTIONS');
export const JSON_API_DECORATOR_READ_ONLY = Symbol('JSON_API_READ_ONLY');
export const JSON_API_DECORATOR_IMMUTABLE = Symbol('JSON_API_IMMUTABLE');
