export const JSON_API_DECORATOR_ENTITY = Symbol('JSON_API_ENTITY');
export const JSON_API_DECORATOR_OPTIONS = Symbol('JSON_API_OPTIONS');
export const GLOBAL_MODULE_OPTIONS_TOKEN = Symbol('GLOBAL_MODULE_OPTIONS');
export const CURRENT_DATA_SOURCE_TOKEN = Symbol('CURRENT_DATA_SOURCE_TOKEN');
export const CURRENT_ENTITY_REPOSITORY = Symbol('CURRENT_ENTITY_REPOSITORY');
export const ZOD_INPUT_QUERY_SCHEMA = Symbol('ZOD_INPUT_QUERY_SCHEMA');
export const ZOD_QUERY_SCHEMA = Symbol('ZOD_INPUT_QUERY_SCHEMA');
export const ZOD_POST_SCHEMA = Symbol('ZOD_POST_SCHEMA');
export const SWAGGER_METHOD = Symbol('SWAGGER_METHOD');
export const ZOD_POST_RELATIONSHIP_SCHEMA = Symbol(
  'ZOD_POST_RELATIONSHIP_SCHEMA'
);
export const ZOD_PATCH_RELATIONSHIP_SCHEMA = Symbol(
  'ZOD_PATCH_RELATIONSHIP_SCHEMA'
);
export const ZOD_PATCH_SCHEMA = Symbol('ZOD_PATCH_SCHEMA');
export const TYPEORM_SERVICE = Symbol('TYPEORM_SERVICE');
export const CONTROL_OPTIONS_TOKEN = Symbol('CONTROL_OPTIONS_TOKEN');

export const PARAMS_RESOURCE_ID = 'id';
export const PARAMS_RELATION_ID = 'relId';
export const PARAMS_RELATION_NAME = 'relName';

export const JSON_API_CONFIG = 'JSON_API_CONFIG';
