version: '3.8'
services:
  postgres:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  pgadmin:
    container_name: 'pgadmin'
    image: 'dpage/pgadmin4:latest'
    hostname: pgadmin
    depends_on:
      - 'postgres'
    environment:
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_DEFAULT_EMAIL=pg.admin@email.com
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - '8000:80'
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - '3306:3306'
    volumes:
      - mysql-db:/var/lib/mysql

volumes:
  db:
    driver: local
  mysql-db:
    driver: local
  pgadmin:
    driver: local
