export { getAll } from './get-all/get-all';
export { getOne } from './get-one/get-one';
export { deleteOne } from './delete-one/delete-one';
export { postOne } from './post-one/post-one';
export { patchOne } from './patch-one/patch-one';
export { getRelationship } from './get-relationship/get-relationship';
export { postRelationship } from './post-relationship/post-relationship';
export { deleteRelationship } from './delete-relationship/delete-relationship';
export { patchRelationship } from './patch-relationship/patch-relationship';
