export * from './user.seed'
export * from './category.seed'
export * from './post.seed'
export * from './tag.seed'
export * from './comment.seed'
export * from './article.seed'
export * from './document.seed'
