export const SUB_QUERY_ALIAS_FOR_PAGINATION = 'subQueryWithLimitOffset';
export const ALIAS_FOR_PAGINATION = 'aliasForPagination';
export const DEFAULT_CONNECTION_NAME = 'default';
export const CURRENT_ENTITY_REPOSITORY = Symbol('CURRENT_ENTITY_REPOSITORY');
export const CURRENT_DATA_SOURCE_TOKEN = Symbol('CURRENT_DATA_SOURCE_TOKEN');
export const CURRENT_ENTITY_MANAGER_TOKEN = Symbol(
  'CURRENT_ENTITY_MANAGER_TOKEN'
);
