export const MAP_CONTROLLER_ENTITY = Symbol('MAP_CONTROLLER_ENTITY');
export const MAP_CONTROLLER_INTERCEPTORS = Symbol(
  'MAP_CONTROLLER_INTERCEPTORS'
);
export const MAP_ENTITY = Symbol('MAP_ENTITY');
export const ZOD_INPUT_OPERATION = Symbol('ZOD_INPUT_OPERATION');
export const ASYNC_ITERATOR_FACTORY = Symbol('ASYNC_ITERATOR_FACTORY');
