export const ENTITY_METADATA_TOKEN = Symbol('ENTITY_METADATA_TOKEN');
export const DEFAULT_ARRAY_TYPE = ['ArrayType', 'EnumArrayType'];
export const CURRENT_DATA_SOURCE_TOKEN = Symbol('CURRENT_DATA_SOURCE_TOKEN');
export const CURRENT_ENTITY_REPOSITORY = Symbol('CURRENT_ENTITY_REPOSITORY');
export const CURRENT_ENTITY_MANAGER_TOKEN = Symbol(
  'CURRENT_ENTITY_MANAGER_TOKEN'
);
