name: ⚙️ Test

on:
  workflow_call:
    inputs:
      mainBranch:
        description: Type for main nx affect
        required: false
        default: "master"
        type: string
    secrets:
      NX_CLOUD_ACCESS_TOKEN:
        required: true
env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: ./.github/actions

      - name: Determine base for NX affected (if not master)
        if: ${{ inputs.mainBranch != 'master' }}
        shell: bash
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0)
          LAST_TAG_HASH=$(git rev-parse "$LAST_TAG")
          CURRENT_COMMIT=$(git rev-parse HEAD)
          echo "Using last tag hash as NX_BASE: $LAST_TAG_HASH"
          echo "Using current commit as NX_HEAD: $CURRENT_COMMIT"
          echo "NX_BASE=$LAST_TAG_HASH" >> $GITHUB_ENV
          echo "NX_HEAD=$CURRENT_COMMIT" >> $GITHUB_ENV

      - name: Determine base for NX affected (if master)
        if: ${{ inputs.mainBranch == 'master' }}
        uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: ${{ inputs.mainBranch }}

      - name: Test
        run: npx nx affected --target=test --parallel=3 --passWithNoTests --exclude='*,!tag:type:publish'

      - name: TS Test
        run: npx nx affected --target=ts-test --parallel=3 --passWithNoTests --exclude='*,!tag:type:publish'
